version: '3'
services:
  backend:
    container_name: pcd-mlease-backend
    build:
      context: ./Backend
      dockerfile: Dockerfile.backend
    ports:
      - "5001:5001"
    environment:
      - MLFLOW_TRACKING_URI=http://pcd-mlease-mlflow:5000
    depends_on:
      - mlflow
    networks:
      - app-network
  frontend:
    container_name: pcd-mlease-frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.11.3
    container_name: pcd-mlease-mlflow
    ports:
      - "5000:5000"
    volumes:
      - mlflow-storage:/mlflow
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow/mlflow.db --default-artifact-root /mlflow/artifacts
    networks:
      - app-network

networks:
  app-network:


volumes:
  mlflow-storage:
